function srp = rainSTORM_createSupResParams()
    srp = struct(...
            'frame_idx', [],...
            'x',[],...
            'y',[],...
            'z',[],...
            'I',[],...
            'sig_x',[],...
            'sig_y',[],...
            'x_std',[],...
            'y_std',[],...
            'avg_brigthness',[],...
            'res',[],...
            'res_Row',[],...
            'res_Col',[],...
            'Sum_signal',[] ...
    );
end

