function loc = rainSTORM_createLocStruct()

settings=struct(...
    'Thresh',[],...
    'allowSig',[],...
    'allowX',[],...
    'estNum',[],...
    'initSig',[],...
    'initX0',[],...
    'maxIts',[],...
    'prevSF',[],...
    'rad',[],...
    'tol',[]...
    );



results=struct(...
    'SupResParams',[],...
    'numberOfFrames',[],...
    'numberOfLocs',[],...
    'sumFrame',[]...
    );



loc=struct(...
    'algo_id',[],...
    'settings',settings,...
    'results',results);
end

